---
title: "explore_handeset"
author: "PenguinJunk"
date: "2024-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import first data set

HanDeSet is a csv, available at [HanDeSeT: Hansard Debates with Sentiment Tags](https://research.manchester.ac.uk/en/datasets/handeset-hansard-debates-with-sentiment-tags). Import it. Errors when trying to print out the resulting tibble because on non-ascii characters so set encoding to utf-8.

```{r handeset.tib}
library(dplyr)
handeset.tib <- read.csv("./data/HanDeSeT.csv", header=TRUE, fileEncoding = "UTF-8") |> dplyr::as_tibble()
```

See what in the dataset.
```{r handeset.tib names}
#names(handeset.tib)
glimpse(handeset.tib)

# motion.party.affiliation and party.affiliation are strings labelling the party of the MP making the motion or responding to the motion, respectively. Convert these to factors:
handeset.tib <- handeset.tib |> 
  mutate(party.affiliation = factor(x = party.affiliation),          motion.party.affiliation = factor(x = motion.party.affiliation))
glimpse(handeset.tib)

# have a look at the distribution per party
handeset.tib |> 
  count(motion.party.affiliation, sort = TRUE)
handeset.tib |> 
  count(party.affiliation, sort = TRUE)

# now start to look at the existing sentiment analysis. 0 is negative, 1 is positive. manual.motion is the sentiment manually applied (using a gold-standard annotation approach) to the motion. 
handeset.tib |> 
  count(motion.party.affiliation, manual.motion, sort = TRUE)

# It looks like motions tend to be negative in sentiment, lets see
handeset.tib |> count(manual.motion)

# What about the sentiment of speeches?
handeset.tib |> count(manual.speech)
```
## Are there science terms?
Start with the motions - look at what these are about

```{r handeset.tib title}
# create a tibble from the the motion title variable
motions_titles.tib <- handeset.tib |> select(title)
# I could turn these into factors since they have standard patterns. I'm not sure this would be useful. There are a few motions that may have scientific content, but not a great deal.
```
Search through the motions and utterances
```{r handeset.tib climate}
srch_term <- "climate"
climate_utt.tib <- handeset.tib |> 
  filter(
    (grepl(srch_term, motion)) |
    (grepl(srch_term, utt1)) |
    (grepl(srch_term, utt2)) |
    (grepl(srch_term, utt3)) |
    (grepl(srch_term, utt4)) |
    (grepl(srch_term, utt5))
    )
glimpse(climate_utt.tib)
climate_utt.tib |> count(manual.motion, manual.speech)
```

```{r handeset.tib ai}
srch_term <- "artificial intelligence"
ai_utt.tib <- handeset.tib |> 
  filter(
    (grepl(srch_term, motion)) |
    (grepl(srch_term, utt1)) |
    (grepl(srch_term, utt2)) |
    (grepl(srch_term, utt3)) |
    (grepl(srch_term, utt4)) |
    (grepl(srch_term, utt5))
    )
glimpse(ai_utt.tib)
ai_utt.tib |> count(manual.motion, manual.speech)
```

```{r handeset.tib science}
srch_term <- "science"
science_utt.tib <- handeset.tib |> 
  filter(
    (grepl(srch_term, motion)) |
    (grepl(srch_term, utt1)) |
    (grepl(srch_term, utt2)) |
    (grepl(srch_term, utt3)) |
    (grepl(srch_term, utt4)) |
    (grepl(srch_term, utt5))
    )
#glimpse(science_utt.tib)
#science_utt.tib |> count(manual.motion, manual.speech)
```

